# Use an official Node runtime as the parent image
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json to the working directory
COPY Frontend/package*.json ./

# Install any dependencies
RUN npm install

# Copy the rest of the application code
COPY Frontend/ ./

# Specify the command to run on container start
CMD [ "npm", "start" ]
