export const specializations = [
    "Anesthesiology",
    "Behavioral Medicine",
    "Cardiology",
    "Clinical Pathology",
    "Dentistry",
    "Dermatology",
    "Emergency and Critical Care",
    "Endocrinology",
    "Equine Medicine",
    "Feline Medicine",
    "Gastroenterology",
    "Internal Medicine",
    "Microbiology",
    "Neurology",
    "Nutrition",
    "Oncology",
    "Ophthalmology",
    "Orthopedic Surgery",
    "Parasitology",
    "Radiology",
    "Reproduction",
    "Surgery",
    "Toxicology",
    "Zoological Medicine"
];